export interface MigrationTableSpec {
  table: string;
  columns: string[];
  defaults?: Record<string, string>;
}

export const migrationTableSpecs: MigrationTableSpec[] = [
  {
    table: 'workspaces',
    columns: [
      'id',
      'profile_id',
      'client_id',
      'origin_id',
      'user_id',
      'project_id',
      'workspace_key',
      'status',
      'metadata_json',
      'created_at',
      'updated_at',
    ],
  },
  {
    table: 'conversations',
    columns: ['id', 'workspace_id', 'title', 'created_at', 'updated_at'],
  },
  {
    table: 'runs',
    columns: [
      'id',
      'workspace_id',
      'profile_id',
      'client_id',
      'kind',
      'skill_id',
      'status',
      'prompt',
      'prompt_mode',
      'current_prompt',
      'context_policy_json',
      'collection_mode',
      'prompt_snapshot_hash',
      'prompt_snapshot_char_count',
      'prompt_snapshot_byte_count',
      'prompt_snapshot_persisted',
      'business_context_hash',
      'artifact_rule_ids_json',
      'idempotency_key',
      'idempotency_fingerprint',
      'last_run_event_id',
      'queued_at',
      'started_at',
      'finished_at',
      'exit_code',
      'signal',
      'error_code',
      'error_message',
      'usage_json',
      'metadata_json',
      'created_at',
      'updated_at',
    ],
    defaults: {
      prompt_mode: "'legacy'",
      current_prompt: 'prompt',
      context_policy_json: 'NULL',
      collection_mode: "'lite'",
      prompt_snapshot_hash: 'NULL',
      prompt_snapshot_char_count: 'NULL',
      prompt_snapshot_byte_count: 'NULL',
      prompt_snapshot_persisted: '0',
      business_context_hash: 'NULL',
      idempotency_key: 'NULL',
      idempotency_fingerprint: 'NULL',
      artifact_rule_ids_json: 'NULL',
      last_run_event_id: 'NULL',
    },
  },
  {
    table: 'run_messages',
    columns: [
      'id',
      'workspace_id',
      'conversation_id',
      'run_id',
      'role',
      'content',
      'thinking_content',
      'events_json',
      'attachments_json',
      'produced_files_json',
      'run_status',
      'last_run_event_id',
      'started_at',
      'ended_at',
      'position',
      'conversation_seq',
      'created_at',
      'updated_at',
    ],
    defaults: {
      thinking_content: "''",
      conversation_seq: 'NULL',
    },
  },
  {
    table: 'artifacts',
    columns: [
      'id',
      'run_id',
      'workspace_id',
      'rule_id',
      'role',
      'relative_path',
      'file_name',
      'mime_type',
      'size',
      'mtime',
      'sha256',
      'metadata_json',
      'created_at',
    ],
  },
  {
    table: 'run_logs',
    columns: ['run_id', 'stdout_log_path', 'stderr_log_path', 'debug_events_log_path', 'created_at'],
  },
  {
    table: 'profile_snapshots',
    columns: ['run_id', 'profile_json', 'created_at'],
  },
  {
    table: 'run_prompt_snapshots',
    columns: [
      'run_id',
      'prompt_snapshot',
      'prompt_snapshot_hash',
      'char_count',
      'byte_count',
      'persisted',
      'created_at',
    ],
  },
  {
    table: 'run_skill_snapshots',
    columns: [
      'run_id',
      'skill_id',
      'skill_name',
      'skill_description',
      'skill_body_hash',
      'skill_body',
      'side_files_manifest_json',
      'persisted',
      'created_at',
    ],
  },
  {
    table: 'run_context_snapshots',
    columns: ['run_id', 'business_context_json', 'business_context_hash', 'persisted', 'created_at'],
  },
  {
    table: 'run_feedback',
    columns: ['id', 'run_id', 'client_id', 'category', 'message', 'metadata_json', 'created_at'],
  },
];
